#!/bin/bash

echo "=== 推送网站到GitHub ==="
echo ""
echo "当前目录: $(pwd)"
echo "Git状态:"
git status
echo ""
echo "请运行以下命令来推送："
echo ""
echo "git push -u origin main"
echo ""
echo "如果提示输入用户名和密码："
echo "- 用户名: 您的GitHub用户名"
echo "- 密码: 您的GitHub Personal Access Token (不是账户密码)"
echo ""
echo "如何创建Personal Access Token:"
echo "1. 访问 https://github.com/settings/tokens"
echo "2. 点击 'Generate new token'"
echo "3. 选择 'repo' 权限"
echo "4. 生成并复制token"
echo ""
echo "推送成功后，请访问："
echo "https://github.com/WeiProduct/AIMeditation/settings/pages"
echo "启用GitHub Pages"